name: travelapp
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
 

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  go_router: ^2.1.4
  shared_preferences: ^2.1.0
  google_sign_in: ^6.1.0
  lottie: ^1.1.0
  location: 
    git:
      url: https://github.com/781flyingdutchman/flutterlocation.git
      ref: V4
      path: packages/location
  geocoding: ^2.0.0
  http: ^0.13.4
  flutter_keyboard_visibility: ^5.4.1
  colorful_safe_area: ^1.0.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.17.0
  image_picker: ^0.8.9
  firebase_core: ^2.14.0
  firebase_database: ^10.1.0
  firebase_auth: ^4.16.0
  syncfusion_flutter_maps: ^21.2.10
  cloud_firestore: ^4.8.2
  uuid: ^3.0.7
  provider: ^6.0.3
  flutter_dotenv: ^5.1.0
  flutter_bloc: ^8.1.3
  loading_animation_widget: ^1.2.0+4
  dismissible_page: ^1.0.2
  connectivity_plus:
    git:
      url: https://github.com/Chamalka20/plus_plugins.git
      ref: main
      path: packages/connectivity_plus
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

 
  #flutter_icons:
  #image_path: "assets/images/Untitled-12.png"
  #ios: true
  #android: true
 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/logo.png
    - assets/images/app bac.jpg
    - assets/images/Rectangle 1.png
    - assets/images/Facebook_Logo_(2019).png.webp
    - assets/images/google-logo-png-webinar-optimizing-for-success-google-business-webinar-13.png
    - assets/images/Untitled 13.png
    - assets/images/Rectangle 1 loging.png
    - assets/images/youtube logo.png
    - assets/images/143784-checklist.json
    - assets/images/hotel.png
    - assets/images/burger.png
    - assets/images/forest.png
    - assets/images/flash.png
    - assets/images/gas-pump.png
    - assets/images/location.png
    - assets/images/star.png
    - assets/images/heart.png
    - assets/images/like.png
    - assets/images/home.png
    - assets/images/map.png
    - assets/images/user.png
    - assets/images/search.png
    - assets/images/like.png
    - assets/images/homeClick.png
    - assets/images/mapClick.png
    - assets/images/searchClick.png
    - assets/images/userClick.png
    - assets/images/likeClick.png
    - assets/images/Boat-Windows-10-Wallpaper.jpg
    - assets/images/cloudy.png
    - assets/images/mostly-cloudy.png
    - assets/images/cloudsAndSun.png
    - assets/images/Partly-sunny.png
    - assets/images/Light-rain.png
    - assets/images/Mostly-Sunny-Day.png
    - assets/images/sunny.png
    - assets/images/PartlyCloudyNightV2.png
    - assets/images/MostlyCloudyNightV2.png
    - assets/images/MostlyClearNight.png
    - assets/images/N210LightRainShowersV2.png
    - assets/images/add.png
    - assets/images/camera.png
    - assets/images/add-black.png
    - assets/images/travel.png
    - assets/images/heartBlack.png
    - assets/images/dry-clean.png
    - assets/images/correct.png
    - assets/images/destination.png
    - assets/images/time-left.png
    - assets/images/chat-arrow.png
    - assets/images/chat-arrow-before.png





  